### ISSUE TITLE
Adding direct NPM support

### ISSUE THREAD

**Issue by aldakata** [revolist/revodropdown#2]
This looks nice but if I want to integrate this with an ongoing project its a headache to integrate.

Could you make it an npm package so it installs with npm install revodropdown ? Way easier to set and go! Is there any way to integrate this dropdowns with my project easyer than cloning the whole project?

Thanks

**Comment by revolist** [comment]
Hello @aldakata, it's present on npm from the beginning:
https://www.npmjs.com/package/@revolist/revo-dropdown

Also, it's available on git packages, you can choose any way you prefer:
https://github.com/revolist/revodropdown/packages/521701
